FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY packages ./packages
COPY apps/admin ./apps/admin
RUN npm install
RUN npm run build --workspace=@nipris/admin

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/admin/.next ./apps/admin/.next
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3001
CMD ["npm", "start", "--workspace=@nipris/admin"]
